# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f67bb496162f87685545c656109e0393f4ae6e1305ff808590868785b82fa8fc6a4f47ffc4eea30c6d8bc3bc28fda8378336aa44736b17be33ca1187a334c8

test:
  secret_key_base: f00550168e353b18a7d8b41229fc2dd2408ea5acff5735907320f99028dd7b4b8e2030366a4e510cadb61f10e7c220e23a793decc76eb49df79883e90d3a7608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
